# Copy this file to build-list.yml
# https://www.json2yaml.com/
list:
  - title: Deploy Demo
    cmd: deploy_demo.js
    config: 'example_param'
  - title: Deploy Self+frontend
    cmd: deploy_self.js
    config: 'frontend'
  - title: Deploy Self
    cmd: deploy_self.js
    config: ''
  - title: Deploy VuePress:example.json
    cmd: deploy_vuepress.js
    config: example.json
  - title: Deploy Nuxt.js:example.json
    cmd: deploy_nuxt.js
    config: example.json
  - title: Deploy Nuxt.js:example-prod.json
    cmd: deploy_nuxt.js
    config: example-prod.json
  - title: Deploy VueCLI3:example.json
    cmd: deploy_vuecli3.js
    config: example.json
  - title: Deploy git Project:example.json
    cmd: deploy_git.js
    config: example.json
